---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  DomainName:
    Description: 'E.g. efio.dk'
    Type: String
    AllowedPattern: '[a-z0-9][a-z0-9-]+\.[a-z0-9]+'
  DomainDescription:
    Description: What is the domain used for?
    Type: String
    MinLength: 3
  ApexType:
    Description: Choose 'Alias' to use AWS specific endpoints
    Type: String
    AllowedValues: [ Disabled, Redirect, A-record, CloudFront ]
    Default: Disabled
  ApexValue:
    Description: IP-address or AWS ARN
    Type: String
    Default: 0.0.0.0
  EnableFastmail:
    Description: Create records required by Fastmail
    Type: String
    AllowedValues: [true, false]
    Default: false
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label: 
          default: "Domain"
        Parameters: 
          - DomainName
          - DomainDescription
      - Label: 
          default: "Website"
        Parameters: 
          - ApexType
          - ApexValue
      - Label: 
          default: "Features"
        Parameters: 
          - EnableFastmail
    ParameterLabels:
      DomainName:
        default: The domain to manage
      DomainDescription:
        default: What is the domain used for?
      ApexType:
        default: Apex type
      ApexValue:
        default: Where should Apex point?
      EnableFastmail:
        default: Enable Fastmail
Conditions:
  CreateFastmail: !Equals [ !Ref EnableFastmail, true ]
  EnableWebsite: !Not [!Equals [!Ref ApexType, Disabled]]
  CreateApexRecord: !Equals [ !Ref ApexType, A-record ]
  CreateRedirect: !Equals [ !Ref ApexType, Redirect ]
  CreateApexCloudfrontAlias: !Equals [ !Ref ApexType, CloudFront ]
Resources:
  HostedZone:
    Type: AWS::Route53::HostedZone
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties: 
      HostedZoneConfig:
        Comment: !Sub '${DomainDescription}. Stack [${AWS::StackName}]'
      HostedZoneTags:
        - Key: Stack
          Value: !Ref AWS::StackName
      Name: !Ref DomainName
  ApexRecord:
    Type: AWS::Route53::RecordSet
    Condition: CreateApexRecord
    Properties:
      Comment: Apex record
      HostedZoneId: !Ref HostedZone
      Name: !Sub '${DomainName}.'
      ResourceRecords:
        - !Ref ApexValue
      TTL: 3600
      Type: A
  ApexCloudfrontAlias:
    Type: AWS::Route53::RecordSet
    Condition: CreateApexCloudfrontAlias
    Properties:
      AliasTarget: 
        DNSName: !Ref ApexValue
        HostedZoneId: Z2FDTNDATAQYW2
      Comment: Apex cloudfront record
      HostedZoneId: !Ref HostedZone
      Name: !Sub '${DomainName}.'
      Type: A

  # Redirect
  ApexRedirect:
    Type: AWS::Route53::RecordSet
    Condition: CreateRedirect
    Properties: 
      AliasTarget: 
        DNSName: s3-website-eu-west-1.amazonaws.com.
        HostedZoneId: Z1BKCTXD74EZPE
      Comment: Apex s3 redirect record
      HostedZoneId: !Ref HostedZone
      Name: !Sub '${DomainName}.'
      Type: A
  # WwwRedirect:
  #   Type: AWS::Route53::RecordSet
  #   Condition: CreateRedirect
  #   Properties: 
  #     AliasTarget: 
  #       DNSName: s3-website-eu-west-1.amazonaws.com.
  #       HostedZoneId: Z1BKCTXD74EZPE
  #     Comment: Www s3 redirect record
  #     HostedZoneId: !Ref HostedZone
  #     Name: !Sub 'www.${DomainName}.'
  #     Type: A
  ApexRedirectBucket:
    Type: AWS::S3::Bucket
    Condition: CreateRedirect
    Properties: 
      BucketName: !Ref DomainName
      WebsiteConfiguration:
        RedirectAllRequestsTo: 
          HostName: !Sub ${ApexValue}
          Protocol: https
  WwwRedirectBucket:
    Type: AWS::S3::Bucket
    Condition: CreateRedirect
    Properties: 
      BucketName: !Sub www.${DomainName}
      WebsiteConfiguration:
        RedirectAllRequestsTo: 
          HostName: !Sub ${ApexValue}
          Protocol: https

  WwwAliasRecord:
    Type: AWS::Route53::RecordSet
    Condition: EnableWebsite
    Properties: 
      Comment: !Sub 'WWW redirect record'
      HostedZoneId: !Ref HostedZone
      Name: !Sub 'www.${DomainName}.'
      ResourceRecords:
        - !Sub ${DomainName}
      TTL: 3600
      Type: CNAME

  Webmail:
    Type: AWS::Route53::RecordSet
    Condition: CreateFastmail
    Properties: 
      Comment: !Sub 'Webmail record'
      HostedZoneId: !Ref HostedZone
      Name: !Sub 'mail.${DomainName}.'
      ResourceRecords:
        - 66.111.4.147
        - 66.111.4.148
      TTL: 3600
      Type: A
  DomainMxRecord:
    Type: AWS::Route53::RecordSet
    Condition: CreateFastmail
    Properties: 
      Comment: !Sub 'Enable e-mail for ${DomainName}'
      HostedZoneId: !Ref HostedZone
      Name: !Ref DomainName
      ResourceRecords:
        - 10 in1-smtp.messagingengine.com
        - 20 in2-smtp.messagingengine.com
      TTL: 3600
      Type: MX
  SubDomainMxRecord:
    Type: AWS::Route53::RecordSet
    Condition: CreateFastmail
    Properties: 
      Comment: !Sub 'Enable e-mail for ${DomainName} subdomains'
      HostedZoneId: !Ref HostedZone
      Name: !Sub '*.${DomainName}.'
      ResourceRecords:
        - 10 in1-smtp.messagingengine.com
        - 20 in2-smtp.messagingengine.com
      TTL: 3600
      Type: MX
  DmarcRecord:
    Type: AWS::Route53::RecordSet
    Condition: CreateFastmail
    Properties: 
      Comment: 'Domain-based Message Authentication, Reporting and Conformance (DMARC)'
      HostedZoneId: !Ref HostedZone
      Name: !Sub '_dmarc.${DomainName}.'
      ResourceRecords:
        - !Sub '"v=DMARC1; p=reject; rua=mailto:postmaster@${DomainName}; ruf=mailto:abuse@${DomainName}; fo=1:d:s; adkim=s; aspf=s; pct=100; rf=afrf; ri=172800; sp=reject"'
      TTL: 3600
      Type: TXT
  SpfRecord:
    Type: AWS::Route53::RecordSet
    Condition: CreateFastmail
    Properties: 
      Comment: 'Sender policy framework (SPF)'
      HostedZoneId: !Ref HostedZone
      Name: !Ref DomainName
      ResourceRecords:
        - '"v=spf1 include:spf.messagingengine.com ~all"'
      TTL: 3600
      Type: TXT
  Dkim1Record:
    Type: AWS::Route53::RecordSet
    Condition: CreateFastmail
    Properties: 
      Comment: 'DomainKeys Identified Mail (DKIM) #1'
      HostedZoneId: !Ref HostedZone
      Name: !Sub 'fm1._domainkey.${DomainName}.'
      ResourceRecords:
        - !Sub fm1.${DomainName}.dkim.fmhosted.com
      TTL: 3600
      Type: CNAME
  Dkim2Record:
    Type: AWS::Route53::RecordSet
    Condition: CreateFastmail
    Properties: 
      Comment: 'DomainKeys Identified Mail (DKIM) #2'
      HostedZoneId: !Ref HostedZone
      Name: !Sub 'fm2._domainkey.${DomainName}.'
      ResourceRecords:
        - !Sub fm2.${DomainName}.dkim.fmhosted.com
      TTL: 3600
      Type: CNAME
  Dkim3Record:
    Type: AWS::Route53::RecordSet
    Condition: CreateFastmail
    Properties: 
      Comment: 'DomainKeys Identified Mail (DKIM) #3'
      HostedZoneId: !Ref HostedZone
      Name: !Sub 'fm3._domainkey.${DomainName}.'
      ResourceRecords:
        - !Sub fm3.${DomainName}.dkim.fmhosted.com
      TTL: 3600
      Type: CNAME
  CaldavSrvRecord:
    Type: AWS::Route53::RecordSet
    Condition: CreateFastmail
    Properties: 
      Comment: Caldav Service Location
      HostedZoneId: !Ref HostedZone
      Name: !Sub '_caldav._tcp.${DomainName}.'
      ResourceRecords:
        - '0 0 0 .'
      TTL: 3600
      Type: SRV
  CaldavSSrvRecord:
    Type: AWS::Route53::RecordSet
    Condition: CreateFastmail
    Properties: 
      Comment: Secure Caldav Service Location
      HostedZoneId: !Ref HostedZone
      Name: !Sub '_caldavs._tcp.${DomainName}.'
      ResourceRecords:
        - '0 1 443 caldav.fastmail.com'
      TTL: 3600
      Type: SRV
  CarddavSrvRecord:
    Type: AWS::Route53::RecordSet
    Condition: CreateFastmail
    Properties: 
      Comment: Carddav Service Location
      HostedZoneId: !Ref HostedZone
      Name: !Sub '_carddav._tcp.${DomainName}.'
      ResourceRecords:
        - '0 0 0 .'
      TTL: 3600
      Type: SRV
  CarddavSSrvRecord:
    Type: AWS::Route53::RecordSet
    Condition: CreateFastmail
    Properties: 
      Comment: Secure Carddav Service Location
      HostedZoneId: !Ref HostedZone
      Name: !Sub '_carddavs._tcp.${DomainName}.'
      ResourceRecords:
        - '0 1 443 carddav.fastmail.com'
      TTL: 3600
      Type: SRV
  Pop3SrvRecord:
    Type: AWS::Route53::RecordSet
    Condition: CreateFastmail
    Properties: 
      Comment: Pop3 Service Location
      HostedZoneId: !Ref HostedZone
      Name: !Sub '_pop3._tcp.${DomainName}.'
      ResourceRecords:
        - '0 0 0 .'
      TTL: 3600
      Type: SRV
  Pop3SSrvRecord:
    Type: AWS::Route53::RecordSet
    Condition: CreateFastmail
    Properties: 
      Comment: Secure Pop3 Service Location
      HostedZoneId: !Ref HostedZone
      Name: !Sub '_pop3s._tcp.${DomainName}.'
      ResourceRecords:
        - '10 1 995 pop.fastmail.com'
      TTL: 3600
      Type: SRV
  ImapSrvRecord:
    Type: AWS::Route53::RecordSet
    Condition: CreateFastmail
    Properties: 
      Comment: IMAP Service Location
      HostedZoneId: !Ref HostedZone
      Name: !Sub '_imap._tcp.${DomainName}.'
      ResourceRecords:
        - '0 0 0 .'
      TTL: 3600
      Type: SRV
  ImapSSrvRecord:
    Type: AWS::Route53::RecordSet
    Condition: CreateFastmail
    Properties: 
      Comment: Secure IMAP Service Location
      HostedZoneId: !Ref HostedZone
      Name: !Sub '_imaps._tcp.${DomainName}.'
      ResourceRecords:
        - '0 1 993 imap.fastmail.com'
      TTL: 3600
      Type: SRV
  SubmissionSrvRecord:
    Type: AWS::Route53::RecordSet
    Condition: CreateFastmail
    Properties: 
      Comment: SMTP Service Location
      HostedZoneId: !Ref HostedZone
      Name: !Sub '_submission._tcp.${DomainName}.'
      ResourceRecords:
        - '0 1 587 smtp.fastmail.com'
      TTL: 3600
      Type: SRV

Outputs:
  HostedZoneId:
    Value: !Ref HostedZone
  NameServer1:
    Value: !Select [0, !GetAtt HostedZone.NameServers]
  NameServer2:
    Value: !Select [1, !GetAtt HostedZone.NameServers]
  NameServer3:
    Value: !Select [2, !GetAtt HostedZone.NameServers]
  NameServer4:
    Value: !Select [3, !GetAtt HostedZone.NameServers]
