---

Parameters:
  DomainName:
    Type: String

  AlternativeNames:
    Type: CommaDelimitedList

Resources:

  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  CloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties: 
      DistributionConfig: 
        Comment: !Sub "Static S3 website for ${DomainName} - Managed by ${AWS::StackName}"
        Enabled: false
        PriceClass: PriceClass_100
        # Aliases: !Split 
        #   - ","
        #   - !Join [ ",", [ !Ref DomainName, !Join [ ",", !Ref AlternativeNames ] ] ]
        DefaultRootObject: index.html

        Origins: 
          - 
            # ConnectionAttempts: 3
            # ConnectionTimeout: 10
            CustomOriginConfig: 
              OriginProtocolPolicy: http-only
              # HTTPPort: 80
              # HTTPSPort: 443
              # OriginKeepaliveTimeout: 5
              # OriginReadTimeout: 30
              # OriginSSLProtocols: 
              #   - String
            DomainName: !GetAtt WebsiteBucket.DomainName
            Id: !Sub ${DomainName}-s3-origin
            # OriginCustomHeaders: 
            #   - OriginCustomHeader
            # OriginPath: String
            # S3OriginConfig: 
            #   S3OriginConfig

        # CacheBehaviors: 
        #   - CacheBehavior

        # CustomErrorResponses: 
        #   - CustomErrorResponse
        DefaultCacheBehavior: 
          TargetOriginId: !Sub ${DomainName}-s3-origin
          AllowedMethods:
            - HEAD
            - GET
            - OPTIONS
          CachedMethods: 
            - HEAD
            - GET
          # CachePolicyId: String
          Compress: true
          DefaultTTL: 86400
          # MinTTL: 0
          # MaxTTL: 31536000
          # FieldLevelEncryptionId: String
          # OriginRequestPolicyId: String
          # SmoothStreaming: Boolean
          # TrustedSigners: 
          #   - String
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: false
            # Headers: []
            # - Host

        # HttpVersion: String
        IPV6Enabled: true
        # Logging: 
        #   Logging
        # Restrictions: 
        #   Restrictions
        # ViewerCertificate: 
        #   ViewerCertificate
        # WebACLId: String

  # # CloudFrontDistributionSslCertificate:
  # #   Type: AWS::CloudFront::Distribution
  # #   Properties:
  # #     DistributionConfig:
  # #       Aliases: !Ref WPDomainAliases
  # #       CacheBehaviors:
  # #       - PathPattern: wp-includes/*
  # #         AllowedMethods:
  # #         - GET
  # #         - HEAD
  # #         - OPTIONS
  # #         DefaultTTL: 900
  # #         MaxTTL: 900
  # #         MinTTL: 900
  # #         ForwardedValues:
  # #           QueryString: true
  # #           Headers:
  # #           - Host
  # #         TargetOriginId: elb
  # #         ViewerProtocolPolicy: redirect-to-https
  # #         Compress: true
  # #       - PathPattern: wp-content/*
  # #         AllowedMethods:
  # #         - DELETE
  # #         - GET
  # #         - HEAD
  # #         - OPTIONS
  # #         - PATCH
  # #         - POST
  # #         - PUT
  # #         DefaultTTL: 900
  # #         MaxTTL: 900
  # #         MinTTL: 900
  # #         ForwardedValues:
  # #           QueryString: true
  # #           Headers:
  # #           - Host
  # #         TargetOriginId: elb
  # #         ViewerProtocolPolicy: redirect-to-https
  # #         Compress: true
  # #       Comment: !Ref 'AWS::StackName'
  # #       DefaultCacheBehavior:
  # #         AllowedMethods:
  # #         - DELETE
  # #         - GET
  # #         - HEAD
  # #         - OPTIONS
  # #         - PATCH
  # #         - POST
  # #         - PUT
  # #         DefaultTTL: 0
  # #         MaxTTL: 0
  # #         MinTTL: 0
  # #         ForwardedValues:
  # #           QueryString: true
  # #           Headers:
  # #           - '*'
  # #           Cookies:
  # #             Forward: all
  # #         TargetOriginId: elb
  # #         ViewerProtocolPolicy: redirect-to-https
  # #         Compress: true
  # #       Enabled: true
  # #       Origins:
  # #       - DomainName: !Ref PublicAlbDnsName
  # #         Id: elb
  # #         CustomOriginConfig:
  # #           OriginProtocolPolicy: https-only
  # #         OriginCustomHeaders: 
  # #         - HeaderName: X-Origin-Secret
  # #           HeaderValue: !Ref OriginSecret
  # #       PriceClass: PriceClass_100
  # #       ViewerCertificate:
  # #         AcmCertificateArn: !Ref CloudFrontAcmCertificate
  # #         SslSupportMethod: sni-only
  # #         MinimumProtocolVersion: TLSv1









Outputs:
  WebsiteBucket:
    Value: !Ref WebsiteBucket
  Test:
    Value: !Join
      - ","
      - - !Ref DomainName
        - !Join [",", !Ref AlternativeNames ]

