---

Parameters:
  DomainName:
    Type: String

  AlternativeNames:
    Type: CommaDelimitedList

  CachingPolicy:
    AllowedValues: [CachingOptimized, CachingDisabled ]
    Type: String

Mappings: 
  ManagedCachePolicy: 
    CachingOptimized: 
      Id: 658327ea-f89d-4fab-a63d-7e88639e58f6
    CachingOptimizedForUncompressedObjects: 
      Id: b2884449-e4de-46a7-ac36-70bc7f1ddd6d
    CachingDisabled: 
      Id: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad

  ManagedOriginRequestPolicy:
    UserAgentRefererHeaders:
      Id: acba4595-bd28-49b8-b9fe-13317c0390fa
    CORSCustomOrigin:
      Id: 59781a5b-3903-41f3-afcb-af62929ccde1
    CORSS3Origin:
      Id: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf
    AllViewer:
      Id: 216adef6-5c7f-47e4-b989-5492eafa07d3

Resources:

  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      VersioningConfiguration:
        Status: Enabled
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  # CloudfrontDistribution:
  Cdn:
    Type: AWS::CloudFront::Distribution
    Properties: 
      DistributionConfig: 
        # Origin settings
        Origins: 
          - DomainName: haveekspert-website-websitebucket-606utyo8qm7i.s3.amazonaws.com
            Id: !Sub ${DomainName}-s3-origin
            CustomOriginConfig: 
              OriginProtocolPolicy: http-only

        # Default Cache behavior
        DefaultCacheBehavior: 
          TargetOriginId: !Sub ${DomainName}-s3-origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - HEAD
            - GET
            - OPTIONS
          CachedMethods: 
            - HEAD
            - GET
          CachePolicyId: !FindInMap [ ManagedCachePolicy, !Ref CachingPolicy, Id ]
          OriginRequestPolicyId: !FindInMap [ ManagedOriginRequestPolicy, CORSS3Origin, Id ]
          Compress: true

        # Distribution settings
        PriceClass: PriceClass_100
        # WebACLId: String
        # Aliases: !Split 
        #   - ","
        #   - !Join [ ",", [ !Ref DomainName, !Join [ ",", !Ref AlternativeNames ] ] ]
        # ViewerCertificate:
        #   AcmCertificateArn: !Ref CloudFrontAcmCertificate
        #   SslSupportMethod: sni-only
        #   MinimumProtocolVersion: TLSv1
        HttpVersion: http2
        DefaultRootObject: index.html
        CustomErrorResponses: 
          - ErrorCachingMinTTL: 300
            ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: /404.html
        # Logging: 
        #   Logging
        IPV6Enabled: true
        Comment: !Sub "Static S3 website for ${DomainName} - Managed by ${AWS::StackName}"
        Enabled: true

Outputs:
  WebsiteBucket:
    Value: !Ref WebsiteBucket
  Test:
    Value: !Join
      - ","
      - - !Ref DomainName
        - !Join [",", !Ref AlternativeNames ]

