---

Parameters:
  DomainName:
    Type: String

  AlternativeNames:
    Type: CommaDelimitedList

  CachingPolicy:
    AllowedValues: [CachingOptimized, CachingDisabled ]
    Type: String

Mappings: 
  ManagedCachePolicy: 
    CachingOptimized: 
      Id: 658327ea-f89d-4fab-a63d-7e88639e58f6
    CachingOptimizedForUncompressedObjects: 
      Id: b2884449-e4de-46a7-ac36-70bc7f1ddd6d
    CachingDisabled: 
      Id: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad

Resources:

  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  CloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties: 
      DistributionConfig: 
        Comment: !Sub "Static S3 website for ${DomainName} - Managed by ${AWS::StackName}"
        Enabled: true
        PriceClass: PriceClass_100
        # Aliases: !Split 
        #   - ","
        #   - !Join [ ",", [ !Ref DomainName, !Join [ ",", !Ref AlternativeNames ] ] ]
        DefaultRootObject: index.html

        Origins: 
          - Id: !Sub ${DomainName}-s3website-origin
            DomainName: !GetAtt WebsiteBucket.DomainName
            CustomOriginConfig: 
              OriginProtocolPolicy: http-only

          # - Id: !Sub ${DomainName}-s3bucket-origin
          #   DomainName: !Sub ${WebsiteBucket}.s3.amazonaws.com
          #   CustomOriginConfig: 
          #     OriginProtocolPolicy: http-only
          #   S3OriginConfig: "" # origin-access-identity/cloudfront/E36VC6OXT542PU
          #   #   S3OriginConfig



                        # "Id": "S3-efio-public-website",
                        # "DomainName": "efio-public-website.s3.amazonaws.com",
                        # "OriginPath": "",
                        # "CustomHeaders": {
                        #     "Quantity": 0
                        # },
                        # "S3OriginConfig": {
                        #     "OriginAccessIdentity": "origin-access-identity/cloudfront/E36VC6OXT542PU"
                        # },

        DefaultCacheBehavior: 
          TargetOriginId: !Sub ${DomainName}-s3website-origin
          AllowedMethods:
            - HEAD
            - GET
            - OPTIONS
          CachedMethods: 
            - HEAD
            - GET
          CachePolicyId: !FindInMap [ ManagedCachePolicy, !Ref CachingPolicy, Id ]
          ViewerProtocolPolicy: redirect-to-https

        # CustomErrorResponses: 
        #   - CustomErrorResponse

        # HttpVersion: String
        IPV6Enabled: true
        # Logging: 
        #   Logging
        # Restrictions: 
        #   Restrictions
        # ViewerCertificate: 
        #   ViewerCertificate
        # WebACLId: String
        # ViewerCertificate:
        #   AcmCertificateArn: !Ref CloudFrontAcmCertificate
        #   SslSupportMethod: sni-only
        #   MinimumProtocolVersion: TLSv1

Outputs:
  WebsiteBucket:
    Value: !Ref WebsiteBucket
  Test:
    Value: !Join
      - ","
      - - !Ref DomainName
        - !Join [",", !Ref AlternativeNames ]

