---

Resources:

  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      # WebsiteConfiguration:
      #   RedirectAllRequestsTo: 
      #     HostName: !Sub ${ApexValue}
      #     Protocol: https
