---

Parameters:
  DomainName:
    Type: String

  AlternativeNames:
    Type: CommaDelimitedList

Resources:

  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  CloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties: 
      DistributionConfig: 
        Comment: !Sub "Static S3 website for ${DomainName} - Managed by ${AWS::StackName}"
        Enabled: true
        PriceClass: PriceClass_100
        # Aliases: !Split 
        #   - ","
        #   - !Join [ ",", [ !Ref DomainName, !Join [ ",", !Ref AlternativeNames ] ] ]
        DefaultRootObject: index.html

        Origins: 
          - 
            # ConnectionAttempts: 3
            # ConnectionTimeout: 10
            CustomOriginConfig: 
              OriginProtocolPolicy: http-only
              # HTTPPort: 80
              # HTTPSPort: 443
              # OriginKeepaliveTimeout: 5
              # OriginReadTimeout: 30
              # OriginSSLProtocols: 
              #   - String
            DomainName: !GetAtt WebsiteBucket.DomainName
            Id: !Sub ${DomainName}-s3-origin
            # OriginCustomHeaders: 
            #   - OriginCustomHeader
            # OriginPath: String
            # S3OriginConfig: 
            #   S3OriginConfig

        # CacheBehaviors: 
        #   - CacheBehavior

        # CustomErrorResponses: 
        #   - CustomErrorResponse
        DefaultCacheBehavior: 
          TargetOriginId: !Sub ${DomainName}-s3-origin
          AllowedMethods:
            - HEAD
            - GET
            - OPTIONS
          CachedMethods: 
            - HEAD
            - GET
          # CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 #  Managed-CachingOptimized
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad #  Managed-CachingDisabled
          # Compress: true
          # DefaultTTL: 0
          # # MinTTL: 0
          # # MaxTTL: 31536000
          # # FieldLevelEncryptionId: String
          # # OriginRequestPolicyId: String
          # # SmoothStreaming: Boolean
          # # TrustedSigners: 
          # #   - String
          # ViewerProtocolPolicy: redirect-to-https
          # ForwardedValues:
          #   QueryString: false
          #   # Headers: []
          #   # - Host

        # HttpVersion: String
        IPV6Enabled: true
        # Logging: 
        #   Logging
        # Restrictions: 
        #   Restrictions
        # ViewerCertificate: 
        #   ViewerCertificate
        # WebACLId: String
        # ViewerCertificate:
        #   AcmCertificateArn: !Ref CloudFrontAcmCertificate
        #   SslSupportMethod: sni-only
        #   MinimumProtocolVersion: TLSv1

Outputs:
  WebsiteBucket:
    Value: !Ref WebsiteBucket
  Test:
    Value: !Join
      - ","
      - - !Ref DomainName
        - !Join [",", !Ref AlternativeNames ]

